version: '3'

services:
  catalogue:
    image: catalogue
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "8990:8990"
      - "8991:8991"
    environment:
      HTTP_PORT: "8990"
      HTTP_ADMIN_PORT: "8991"
      HIBERNATE_DEBUG_LEVEL: "DEBUG"
      PERSISTENCE_UNIT: "catalogueManager"
      JDBC_DRIVER: "org.postgresql.Driver"
      JDBC_URL: "jdbc:postgresql://postgres/catalogue"
      JDBC_USER: "spices"
      JDBC_PASSWORD: "spices"
      HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQL95Dialect"
      HBM_AUTO: "create-drop"
      SHOW_SQL: "true"
      FORMAT_SQL: "true"
      FLUSH_MODE: "COMMIT"

  postgres:
    image: postgres:10.3-alpine
    command: "postgres"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "spices"
      POSTGRES_PASSWORD: "spices"
      POSTGRES_DB: "catalogue"
    ports:
      - "5432:5432"