version: '3'

services:
  catalogue:
    image: catalogue
    depends_on:
      - postgres
    ports:
      - "8990:8990"
      - "8991:8991"
  postgres:
    image: postgres:10.3-alpine
    command: "postgres"
    environment:
      POSTGRES_USER: "spices"
      POSTGRES_PASSWORD: "spices"
      POSTGRES_DB: "catalogue"
    ports:
      - "5432:5432"